// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
[TestFixture]
public class UnitTest1
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void ShowWelcomeText()
    {
        driver.Navigate().GoToUrl("https://localhost:7236/");
        var elements = driver.FindElements(By.XPath("//h1[contains(.,\'Welcome\')]"));
        Assert.That(elements.Count > 0);
    }

    [Test]
    public void BasicAssertion()
    {
        Assert.Pass();
    }
}
